global using OpenQA.Selenium;
global using OpenQA.Selenium.Support.UI;
global using HtmlAgilityPack;
global using System.Collections.Generic;
global using System.IO;
global using System;
global using System.Text.RegularExpressions;
global using System.Linq;
global using NLog;
global using System.Text;
global using System.Xml.XPath;
global using System.Threading.Tasks;
global using MangaLightNovelWebScrape;
global using static Src.Models.Constants;